[package]
name = "flipperzero-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = "0.61.0"
clap = { version = "4.0.16", features = ["cargo"] }
csv = "1.1.6"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.86"
shlex = "1.1.0"
